export const message = {
  success: 'OK',
  errr: 'Error',
  error_message: 'Error en el servidor',
  success_long: 'Operación realizada exitosamente',
  create_success: 'Peticion de creacion procesada',
  create_success_long: 'Transacción efectuada exitosamente',
  accepted: 'Peticion Aceptada',
  accepted_long: 'La solicitud ha sido aceptada exitosamente',
  no_content: 'Respuesta sin contenido',
  no_content_long: 'Cuerpo sin contenido',
  bad_request: 'Peticion con Datos Erroneos',
  bad_request_long: 'El registro solicitado no existe',
  duplicate_entry: '¡Entrada duplicada!',
  duplicate_data: '¡Dato ya registrado en la BD!',
  duplicate_entry_long: 'Ocurrió un error al procesar tu solicitud',
  unauthorized: 'Acceso No Autorizado',
  unauthorized_long: 'Introduzca credenciales válidas',
  forbidden: 'Acceso Prohibido',
  forbidden_long: 'Introduzca credenciales válidas',
  not_found: 'Peticion no encontrada',
  not_found_long: 'El registro solicitado no existe',
  unprocessable_entity: '¡Entidad no procesada!',
  update: 'Actualizacion exitosa',
  delete: 'Eliminacion  exitosa',
  unprocessable_entity_long: 'Hubo un problema al procesar la entidad',
  internal_server_error: 'Error interno en el servidor',
  internal_server_error_long: 'Ha ocurrido un error inesperado',
  not_implemented: 'Servicio no implementado',
  not_implemented_long: 'Ha ocurrido un error inesperado',
  service_unavailable: 'Servicio no disponible',
  service_unavailable_long: 'Ha ocurrido un error inesperado',
  error: 'Error interno en el servidor',
  error_long: 'Ha ocurrido un error inesperado',
  response_success: '¡Exitoso!',
  response_success_long: 'Operación realizada exitosamente',
  response_post_success: '¡Exitoso!',
  response_post_success_long: 'Transacción efectuada exitosamente',
  record_not_found: 'El registro no existe o fue eliminado'
}
